name: .NET

on:
  push:
    branches: [ main ]


  env:
    AZURE_FUNCTIONAPP_NAME: CandidateManager.Functions  # set this to your application's name
    AZURE_FUNCTIONAPP_PACKAGE_PATH: './src/CandidateManager.Functions'    # set this to the path to your web app project, defaults to the repository root
    DOTNET_VERSION: '5.0.x'              

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: List Runtimes
      shell: bash
      run: |
        dotnet --list-runtimes
        dotnet --list-sdks
        

    # - name: Restore dependencies
    #   run: dotnet restore

    # - name: Build
    #   run: dotnet build --no-restore

    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
