name: .NET

on:
  push:
    branches: [ main ]


env:
  AZURE_FUNCTIONAPP_NAME: CandidateManager.Functions  # set this to your application's name
  TESTAPP_PACKAGE_PATH: './src/CandidateManager.Tests'    # set path to test project 
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './src/CandidateManager.Functions'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '5.0.x'     
  CONFIGURATION: Release         

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET 3.1 Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Setup .NET ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration ${{ env.CONFIGURATION }} --output ./output      
        popd

    - name: 'Run unit tests'
      shell: bash
      run: |
        pushd './${{ env.TESTAPP_PACKAGE_PATH }}'
        dotnet test --configuration ${{ env.CONFIGURATION }}       
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

